dataset:
  path: bdsaglam/drop-musique-mini
  name: default
  split: train

qa:
  model: llama-3-8b
  temperature: 0.0
  top_p: 0.9999
  system_prompt: direct/format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: manual/direct.json
  n_shot: 0
  n_sc: 1

run: 1
