dataset:
  path: bdsaglam/musique-sweep
  name: answerable
  split: train

qa:
  model: llama-3-70b-tgi
  temperature: 0.7
  system_prompt: direct/excellent-format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: auto/direct.json
  n_shot: 3

run: 3
