dataset:
  path: bdsaglam/musique
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 1.0
  system_prompt: standard/minimal-output-format.txt
  user_prompt_template: cq.txt
  few_shot_examples: empty.json

run: 1
