dataset:
  path: bdsaglam/musique-sweep
  name: answerable
  split: train

qa:
  model: llama-3-70b-tgi
  temperature: 1.5
  system_prompt: ccot/excellent-format-thought.txt
  user_prompt_template: cq.txt
  few_shot_examples: auto/ccot.json
  n_shot: 6

run: 2
