dataset:
  path: bdsaglam/musique-sweep
  name: answerable
  split: train

qa:
  model: llama-3-70b-tgi
  temperature: 1.5
  system_prompt: cte/excellent-format-triplets-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: auto/cte.json
  n_shot: 2

run: 3
