dataset:
  path: bdsaglam/musique
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  system_prompt: cot/format-minimal.txt
  user_prompt_template: cq.txt
  few_shot_examples: cot-2-shot.json

run: 2
