dataset:
  path: bdsaglam/musique-sweep
  name: answerable
  split: train

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  system_prompt: ccot/excellent-format-thought.txt
  user_prompt_template: cq.txt
  few_shot_examples: auto/ccot.json
  n_shot: 3

run: 1
