dataset:
  path: bdsaglam/musique
  name: answerable
  split: train

qa:
  model: deepseek-r1-llama-70b
  temperature: 0.0
  system_prompt: empty.txt
  user_prompt_template: icq-format.txt
  few_shot_examples: manual/reasoning.json
  n_shot: 0
  n_sc: 1

run: 1
