dataset:
  path: bdsaglam/musique
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  system_prompt: no-role.txt
  user_prompt_template: cq.txt
  few_shot_examples: empty.json

run: 1
