dataset:
  path: bdsaglam/musique
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.0
  system_prompt: direct/format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: semi/direct.json
  n_shot: 0
  n_sc: 1

run: 1
