dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: train

qa:
  model: gpt-4o-mini
  temperature: 0.1
  system_prompt: direct/helpful-output-format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: direct/direct-2-shot.json
  n_shot: 0

run: 0
