dataset:
  path: bdsaglam/musique
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.5
  system_prompt: direct/minimal-output-format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: direct-2-shot.json

run: 3
