dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  system_prompt: standard/helpful-output-format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: standard-2-shot.json

run: 3
