dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: train

qa:
  model: gpt-4o-mini
  temperature: 0.1
  system_prompt: cte/excellent-format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: cte/cte-2-shot-delim-1.json
  n_shot: 0

run: 0
