dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 1.0
  system_prompt: cte/format-relevant-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: empty.json

run: 2
