dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.3
  system_prompt: cot/excellent-format-reasoning.txt
  user_prompt_template: cq.txt
  few_shot_examples: empty.json

run: 2
