dataset:
  path: bdsaglam/musique-sweep
  name: answerable
  split: train

qa:
  model: llama-3-70b-tgi
  temperature: 2.0
  system_prompt: cte/format-triplets-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: auto/cte.json
  n_shot: 0

run: 3
