dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: train

qa:
  model: llama-3-70b-tgi
  temperature: 0.7
  system_prompt: cok/adapted.txt
  user_prompt_template: cq.txt
  few_shot_examples: manual/cok.json
  n_shot: 2

run: 1
