dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 0.1
  system_prompt: cot/format-thought.txt
  user_prompt_template: cq.txt
  few_shot_examples: auto/cot.json
  n_shot: 6

run: 3
