dataset:
  path: bdsaglam/musique
  name: answerable
  split: validation

qa:
  model: llama-3-70b-tgi
  temperature: 2.0
  system_prompt: standard/helpful-output-format-few.txt
  user_prompt_template: cq.txt
  few_shot_examples: empty.json

run: 3
